// @title           Sim1.0 API
// @version         1.0
// @description     Possession-by-possession NBA game simulator API.
// @host            localhost:8080
// @BasePath        /
package main

import (
	"log"
	"net/http"
	"os"

	"github.com/chengyang/sim1.0/backend/internal/api"
	"github.com/chengyang/sim1.0/backend/internal/config"

	_ "github.com/chengyang/sim1.0/backend/docs" // generated by swag init
)

func main() {
	cfg, err := config.Load(config.Dir())
	if err != nil {
		log.Fatal(err)
	}

	addr := os.Getenv("ADDR")
	if addr == "" {
		addr = ":8080"
	}

	h := api.NewHandlers(cfg)
	log.Printf("Sim1.0 API on %s (Swagger: http://localhost%s/swagger/index.html)", addr, addr)
	log.Fatal(http.ListenAndServe(addr, api.NewRouter(h)))
}
