// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/simulate": {
            "post": {
                "description": "Runs possessions until the game clock ends. Same seed produces the same game.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simulate"
                ],
                "summary": "Simulate a full game",
                "parameters": [
                    {
                        "description": "Home/away team ids and optional seed",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.SimulateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SimulateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/simulate/season": {
            "post": {
                "description": "Runs every game in the 2025-26 schedule and returns standings with W, L, streak, last-10, home/away records, PPG, OPPG, and DIFF.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "simulate"
                ],
                "summary": "Simulate a full NBA regular season",
                "parameters": [
                    {
                        "description": "Optional seed for reproducibility",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SimulateSeasonRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SimulateSeasonResponse"
                        }
                    }
                }
            }
        },
        "/teams": {
            "get": {
                "description": "Returns team ids and names from teams.json",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "teams"
                ],
                "summary": "List all teams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ListTeamsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "unknown team id"
                }
            }
        },
        "internal_api.GameEvent": {
            "type": "object",
            "properties": {
                "away_score": {
                    "type": "integer",
                    "example": 98
                },
                "clock_sec": {
                    "type": "integer",
                    "example": 45
                },
                "home_score": {
                    "type": "integer",
                    "example": 105
                },
                "period": {
                    "type": "string",
                    "example": "Q4"
                },
                "points": {
                    "type": "integer",
                    "example": 2
                },
                "possession": {
                    "type": "integer",
                    "example": 1
                },
                "team": {
                    "type": "string",
                    "example": "home"
                },
                "text": {
                    "type": "string",
                    "example": "Lakers make_2pt (2 pts)"
                },
                "type": {
                    "type": "string",
                    "example": "make_2pt"
                }
            }
        },
        "internal_api.GameState": {
            "type": "object",
            "properties": {
                "away_id": {
                    "type": "string",
                    "example": "BOS"
                },
                "away_name": {
                    "type": "string",
                    "example": "Celtics"
                },
                "away_score": {
                    "type": "integer",
                    "example": 98
                },
                "clock_sec": {
                    "type": "integer",
                    "example": 0
                },
                "home_id": {
                    "type": "string",
                    "example": "LAL"
                },
                "home_name": {
                    "type": "string",
                    "example": "Lakers"
                },
                "home_score": {
                    "type": "integer",
                    "example": 105
                },
                "offense": {
                    "description": "omitted when status is final",
                    "type": "string",
                    "example": "home"
                },
                "period": {
                    "type": "string",
                    "example": "Q4"
                },
                "possession": {
                    "type": "integer",
                    "example": 201
                },
                "quarter": {
                    "type": "integer",
                    "example": 4
                },
                "status": {
                    "type": "string",
                    "example": "final"
                }
            }
        },
        "internal_api.ListTeamsResponse": {
            "type": "object",
            "properties": {
                "teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.TeamOption"
                    }
                }
            }
        },
        "internal_api.SimulateRequest": {
            "type": "object",
            "properties": {
                "away_team_id": {
                    "type": "string",
                    "example": "BOS"
                },
                "home_team_id": {
                    "type": "string",
                    "example": "LAL"
                },
                "seed": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "internal_api.SimulateResponse": {
            "type": "object",
            "properties": {
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.GameEvent"
                    }
                },
                "seed": {
                    "type": "integer",
                    "example": 42
                },
                "state": {
                    "$ref": "#/definitions/internal_api.GameState"
                },
                "truncated": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_api.SimulateSeasonRequest": {
            "type": "object",
            "properties": {
                "seed": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "internal_api.SimulateSeasonResponse": {
            "type": "object",
            "properties": {
                "season": {
                    "type": "string"
                },
                "seed": {
                    "type": "integer"
                },
                "standings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.TeamSeasonStat"
                    }
                }
            }
        },
        "internal_api.TeamOption": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "LAL"
                },
                "name": {
                    "type": "string",
                    "example": "Lakers"
                }
            }
        },
        "internal_api.TeamSeasonStat": {
            "type": "object",
            "properties": {
                "away_record": {
                    "type": "string",
                    "example": "24-17"
                },
                "diff": {
                    "type": "number",
                    "example": 4.4
                },
                "home_record": {
                    "type": "string",
                    "example": "30-11"
                },
                "l": {
                    "type": "integer",
                    "example": 28
                },
                "last_10": {
                    "type": "string",
                    "example": "7-3"
                },
                "oppg": {
                    "type": "number",
                    "example": 109.8
                },
                "ppg": {
                    "type": "number",
                    "example": 114.2
                },
                "streak": {
                    "type": "string",
                    "example": "W3"
                },
                "team_id": {
                    "type": "string",
                    "example": "LAL"
                },
                "team_name": {
                    "type": "string",
                    "example": "Lakers"
                },
                "w": {
                    "type": "integer",
                    "example": 54
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Sim1.0 API",
	Description:      "Possession-by-possession NBA game simulator API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
